project_id = "vxohmauydonsetwznhcn"

[functions.transform-learning-style]
verify_jwt = false

[functions.extract-file-text]
verify_jwt = false

[functions.transform-with-gemini]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.gemini-text-manipulator]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false