// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxohmauydonsetwznhcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4b2htYXV5ZG9uc2V0d3puaGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTE2NDksImV4cCI6MjA3MzM2NzY0OX0.sJHDHat3TTUxKQvqbIzUEKiwgTaCyrmbXZH4TxbZNj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});